Andras-Csanyi/DigitalLibrary

src/Utils/DiLibHttpClient/DiLibHttpClient.cs

#17 jsonconvert settings fix

---

src/MasterData/MasterData.WebApi.Client/Client/MasterDataHttpClient.Dimension.cs
src/MasterData/MasterData.WebApi.Client/Client/MasterDataHttpClient.DimensionStructure.cs
src/MasterData/MasterData.WebApi.Client/Client/MasterDataHttpClient.SourceFormat.cs
src/Utils/DiLibHttpClient/DiLibHttpClient.cs
src/Utils/DiLibHttpClient/IDiLibHttpClient.cs

#27 method names with Async end

---

src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Tests/ControlPanel.BusinessLogic.Implementations.Tests.csproj
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/ControlPanel.BusinessLogic.Implementations.csproj
src/ControlPanel/ControlPanel.Ctx/ControlPanel.Ctx.csproj
src/Host/WebApp/WebApp.csproj
src/Host/WebUi/WebUi.csproj
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/MasterData.BusinessLogic.Implementations.Tests.csproj
src/MasterData/MasterData.BusinessLogic.Implementations/MasterData.BusinessLogic.Implementations.csproj
src/MasterData/MasterData.Controllers.Integration.Tests/MasterData.Controllers.Integration.Tests.csproj
src/MasterData/MasterData.Ctx/MasterData.Ctx.csproj
src/Utils/IntegrationTestFactories/IntegrationTestFactories.csproj

#31 ASpNetCore nuget packages version bump

---

src/Utils/DiLibHttpClient/IDiLibHttpClient.cs

#41 DiLibHttpClient interface is documented

---

src/MasterData/MasterData.WebApi.Client/Client/IMasterDataHttpClient.DimensionStructure.cs
src/MasterData/MasterData.WebApi.Client/Client/IMasterDataHttpClient.Sourceformat.cs
src/MasterData/MasterData.WebApi.Client/Client/IMasterDataHttpClient.cs
src/MasterData/MasterData.WebApi.Client/Client/MasterDataHttpClient.DimensionStructure.cs
src/MasterData/MasterData.WebApi.Client/Client/MasterDataHttpClient.SourceFormat.cs

#49 MasterDataHttpClient documented partially

---

src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Unit.Tests/ControlPanel.BusinessLogic.Implementations.Unit.Tests.csproj
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/ControlPanel.BusinessLogic.Implementations.csproj
src/ControlPanel/ControlPanel.Ctx/ControlPanel.Ctx.csproj
src/ControlPanel/ControlPanel.Validators/ControlPanel.Validators.csproj
src/Host/WebApp/WebApp.csproj
src/Host/WebUi/WebUi.csproj
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/MasterData.BusinessLogic.Implementations.Tests.csproj
src/MasterData/MasterData.BusinessLogic.Implementations/MasterData.BusinessLogic.Implementations.csproj
src/MasterData/MasterData.Controllers.Integration.Tests/MasterData.Controllers.Integration.Tests.csproj
src/MasterData/MasterData.Ctx/MasterData.Ctx.csproj
src/MasterData/MasterData.Validators/MasterData.Validators.csproj
src/Utils/IntegrationTestFactories/IntegrationTestFactories.csproj

Nuget bump

---

src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Unit.Tests/ControlPanel.BusinessLogic.Implementations.Unit.Tests.csproj
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/ControlPanel.BusinessLogic.Implementations.csproj
src/ControlPanel/ControlPanel.Ctx/ControlPanel.Ctx.csproj
src/ControlPanel/ControlPanel.WebApi.Client.Unit.Tests/ControlPanel.WebApi.Client.Unit.Tests.csproj
src/Host/WebApp/WebApp.csproj
src/Host/WebUi/WebUi.csproj
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/MasterData.BusinessLogic.Implementations.Tests.csproj
src/MasterData/MasterData.BusinessLogic.Implementations/MasterData.BusinessLogic.Implementations.csproj
src/MasterData/MasterData.Controllers.Integration.Tests/MasterData.Controllers.Integration.Tests.csproj
src/MasterData/MasterData.Controllers.Unit.Tests/MasterData.Controllers.Unit.Tests.csproj
src/MasterData/MasterData.Ctx/MasterData.Ctx.csproj
src/MasterData/MasterData.DomainModel.Unit.Tests/MasterData.DomainModel.Unit.Tests.csproj
src/MasterData/MasterData.Validators.Test/MasterData.Validators.Test.csproj
src/Utils/IntegrationTestFactories/IntegrationTestFactories.csproj

Nuget packages bump to 3.1.3

---

src/Host/WebUi/WebUi.csproj

Blazorstrap upgrade

---

src/Host/WebUI.Test/Services/DomainEntityHelperService_Should.cs
src/Host/WebUI.Test/SourceFormatBuilderService/AddDimensionStructureRootAsync_Should.cs
src/Host/WebUI.Test/SourceFormatBuilderService/AddDimensionStructureRootAsync_Validation_Should.cs
src/Host/WebUI.Test/SourceFormatBuilderService/AddOrUpdateDocumentStructureToTreeAsync_Update_Should.cs
src/Host/WebUI.Test/SourceFormatBuilderService/Ctor_Validation_Should.cs
src/Host/WebUI.Test/SourceFormatBuilderService/DeleteDimensionStructureRootAsync_Validation_Should.cs
src/Host/WebUI.Test/SourceFormatBuilderService/OnUpdate_Validation_Should.cs
src/Host/WebUI.Test/SourceFormatBuilderService/RemoveItemFromTreeAsync_Should.cs
src/Host/WebUI.Test/SourceFormatBuilderService/ReplaceDimensionStructureInTheTreeAsync_Should.cs
src/Host/WebUI.Test/SourceFormatBuilderService/SaveNewRootDimensionStructureHandlerAsync_Should.cs
src/Host/WebUI.Test/SourceFormatBuilderService/TestBase.cs

The goal is having WebUi.Tests project as a zero warning project in order to gain experience about its PITA factor. On the other hand, excellent opportunity for learning.
Gaining experience.

Chore: Zero warning WebUi.Tests project

---

src/ControlPanel/ControlPanel.Validators/ControlPanel.Validators.csproj
src/MasterData/MasterData.Validators/MasterData.Validators.csproj

chore: FluentValidation bump

---

src/ControlPanel/ControlPanel.BusinessLogic.Exceptions/ControlPanel.BusinessLogic.Exceptions.csproj
src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Unit.Tests/ControlPanel.BusinessLogic.Implementations.Unit.Tests.csproj
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/ControlPanel.BusinessLogic.Implementations.csproj
src/ControlPanel/ControlPanel.BusinessLogic.Interfaces/ControlPanel.BusinessLogic.Interfaces.csproj
src/ControlPanel/ControlPanel.Ctx/ControlPanel.Ctx.csproj
src/ControlPanel/ControlPanel.DomainModel/ControlPanel.DomainModel.csproj
src/ControlPanel/ControlPanel.Validators/ControlPanel.Validators.csproj
src/ControlPanel/ControlPanel.WebApi.Api/ControlPanel.WebApi.Api.csproj
src/ControlPanel/ControlPanel.WebApi.Client.Unit.Tests/ControlPanel.WebApi.Client.Unit.Tests.csproj
src/ControlPanel/ControlPanel.WebApi.Client/ControlPanel.WebApi.Client.csproj
src/Database.DigitalLibrary/Database.DigitalLibrary.csproj
src/MasterData/MasterData.BusinessLogic.Exceptions/MasterData.BusinessLogic.Exceptions.csproj
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/MasterData.BusinessLogic.Implementations.Tests.csproj
src/MasterData/MasterData.BusinessLogic.Implementations/MasterData.BusinessLogic.Implementations.csproj
src/MasterData/MasterData.BusinessLogic.Interfaces/MasterData.BusinessLogic.Interfaces.csproj
src/MasterData/MasterData.Ctx/MasterData.Ctx.csproj
src/MasterData/MasterData.DomainModel.Unit.Tests/MasterData.DomainModel.Unit.Tests.csproj
src/MasterData/MasterData.DomainModel/MasterData.DomainModel.csproj
src/MasterData/MasterData.Features/MasterData.Features.csproj
src/MasterData/MasterData.Validators/MasterData.Validators.csproj
src/MasterData/MasterData.Web.Api.Features/MasterData.Web.Api.Features.csproj
src/MasterData/MasterData.Web.Api/MasterData.Web.Api.csproj

chore: FxCopAnalyzers bump

---

src/ControlPanel/ControlPanel.Controllers/ControlPanel.Controllers.csproj
src/Host/DiLib.FAST.Widgets.Tests/DiLib.FAST.Widgets.Tests.csproj
src/Host/DiLib.FAST.Widgets/DiLib.FAST.Widgets.csproj
src/Host/FAST.Components.Tests/FAST.Components.Tests.csproj
src/Host/FAST.Components/FAST.Components.csproj
src/Host/WebApp/WebApp.csproj
src/Host/WebUI.Test/WebUI.Test.csproj
src/Host/WebUi/WebUi.csproj
src/MasterData/MasterData.BusinessLogic.ViewModels.Unit.Tests/MasterData.BusinessLogic.ViewModels.Unit.Tests.csproj
src/MasterData/MasterData.BusinessLogic.ViewModels/MasterData.BusinessLogic.ViewModels.csproj
src/MasterData/MasterData.Controllers.Integration.Tests/MasterData.Controllers.Integration.Tests.csproj
src/MasterData/MasterData.Controllers.Unit.Tests/MasterData.Controllers.Unit.Tests.csproj
src/MasterData/MasterData.Controllers/MasterData.Controllers.csproj
src/MasterData/MasterData.DomainModel.Interfaces/MasterData.DomainModel.Interfaces.csproj
src/MasterData/MasterData.Validators.Test/MasterData.Validators.Test.csproj
src/MasterData/MasterData.Validators.TestData/MasterData.Validators.TestData.csproj
src/MasterData/MasterData.WebApi.Client/MasterData.WebApi.Client.csproj
src/Utils/ControlPanel.DataSample/ControlPanel.DataSample.csproj
src/Utils/DiLibHttpClient/DiLibHttpClient.csproj
src/Utils/Guard.Tests/Guard.Tests.csproj
src/Utils/Guards/Guards.csproj
src/Utils/IntegrationTestFactories/IntegrationTestFactories.csproj
src/Utils/MasterData.DataSample/MasterData.DataSample.csproj

Microsoft.CodeAnalysis.FxCopAnalyzers

chore: add Microsoft.CodeAnalysis.FxCopAnalyzers

---

src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Unit.Tests/ControlPanel.BusinessLogic.Implementations.Unit.Tests.csproj
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/ControlPanel.BusinessLogic.Implementations.csproj
src/ControlPanel/ControlPanel.Ctx/ControlPanel.Ctx.csproj
src/Host/DiLib.FAST.Widgets/DiLib.FAST.Widgets.csproj
src/Host/FAST.Components/FAST.Components.csproj
src/Host/WebApp/WebApp.csproj
src/Host/WebUi/WebUi.csproj
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/MasterData.BusinessLogic.Implementations.Tests.csproj
src/MasterData/MasterData.BusinessLogic.Implementations/MasterData.BusinessLogic.Implementations.csproj
src/MasterData/MasterData.Controllers.Integration.Tests/MasterData.Controllers.Integration.Tests.csproj
src/MasterData/MasterData.Ctx/MasterData.Ctx.csproj
src/Utils/IntegrationTestFactories/IntegrationTestFactories.csproj

chore: Update to .Net Core 3.1.7

---

src/ControlPanel/ControlPanel.Validators/ControlPanel.Validators.csproj
src/MasterData/MasterData.Validators/MasterData.Validators.csproj

Chore: FluentValidation to 9.1.3.

---

src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Unit.Tests/ControlPanel.BusinessLogic.Implementations.Unit.Tests.csproj
src/ControlPanel/ControlPanel.WebApi.Client.Unit.Tests/ControlPanel.WebApi.Client.Unit.Tests.csproj
src/Host/DiLib.FAST.Widgets.Tests/DiLib.FAST.Widgets.Tests.csproj
src/Host/FAST.Components.Tests/FAST.Components.Tests.csproj
src/Host/WebUI.Test/WebUI.Test.csproj
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/MasterData.BusinessLogic.Implementations.Tests.csproj
src/MasterData/MasterData.BusinessLogic.ViewModels.Unit.Tests/MasterData.BusinessLogic.ViewModels.Unit.Tests.csproj
src/MasterData/MasterData.Controllers.Integration.Tests/MasterData.Controllers.Integration.Tests.csproj
src/MasterData/MasterData.Controllers.Unit.Tests/MasterData.Controllers.Unit.Tests.csproj
src/MasterData/MasterData.DomainModel.Unit.Tests/MasterData.DomainModel.Unit.Tests.csproj
src/MasterData/MasterData.Features/MasterData.Features.csproj
src/MasterData/MasterData.Validators.Test/MasterData.Validators.Test.csproj
src/Utils/Guard.Tests/Guard.Tests.csproj
src/Utils/IntegrationTestFactories/IntegrationTestFactories.csproj

Microsoft.NET.Test.Sdk to 16.7.1

chore: Microsoft.NET.Test.Sdk to 16.7.1

---

src/ControlPanel/ControlPanel.Validators/ControlPanel.Validators.csproj
src/MasterData/MasterData.Validators/MasterData.Validators.csproj

FluentValidation 9.2.0

---

src/Host/FAST.Components/FAST.Components.csproj

Microsoft.AspNetCore.Components.Web to 3.1.7

Microsoft.AspNetCore.Components to 3.1.7

---

src/Host/DiLib.FAST.Widgets.Tests/DiLib.FAST.Widgets.Tests.csproj
src/Host/FAST.Components.Tests/FAST.Components.Tests.csproj

chore: bunit to preview9

---

src/Host/WebUI.Test/SourceFormatBuilderService/SaveNewRootDimensionStructureHandlerAsync_Should.cs
src/Host/WebUI.Test/SourceFormatBuilderService/TestBase.cs
src/Host/WebUi/Components/SourceFormatBuilder/ISourceFormatBuilderService.cs
src/Host/WebUi/Components/SourceFormatBuilder/SourceFormatBuilderService.cs
src/MasterData/MasterData.DomainModel/DomainModel/DimensionStructure.cs

Enabling test cases for SaveNewRootDimensionStructure method.
They were disabled due to some reasons.

Chore: enabling Save New RootDimensionStructure test cases

---

src/Utils/Guards/Check.cs

Guards get a more detailed default message.
#94

Default error message for Guards

---

src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Unit.Tests/ControlPanel.BusinessLogic.Implementations.Unit.Tests.csproj
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/ControlPanel.BusinessLogic.Implementations.csproj
src/ControlPanel/ControlPanel.Ctx/ControlPanel.Ctx.csproj
src/Host/DiLib.FAST.Widgets/DiLib.FAST.Widgets.csproj
src/Host/FAST.Components/FAST.Components.csproj
src/Host/WebApp/WebApp.csproj
src/Host/WebUi/WebUi.csproj
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/MasterData.BusinessLogic.Implementations.Tests.csproj
src/MasterData/MasterData.BusinessLogic.Implementations/MasterData.BusinessLogic.Implementations.csproj
src/MasterData/MasterData.Controllers.Integration.Tests/MasterData.Controllers.Integration.Tests.csproj
src/MasterData/MasterData.Ctx/MasterData.Ctx.csproj
src/Utils/IntegrationTestFactories/IntegrationTestFactories.csproj

Upgrade dotNet libraries to 3.1.8.

Chore: dotNet 3.1.8.

---

src/ControlPanel/ControlPanel.Validators/ControlPanel.Validators.csproj
src/MasterData/MasterData.Validators/MasterData.Validators.csproj

Chore: FluentValidation to 9.2.2

---

src/MasterData/MasterData.BusinessLogic.Implementations.Tests/MasterData.BusinessLogic.Implementations.Tests.csproj

Chore: Specflow nuget upgrade to 3.4.14

---

src/MasterData/MasterData.BusinessLogic.Implementations.Tests.Entities/GenericEntity.cs
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/DimensionStructure.DeleteAsync.Validation.feature
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/DimensionStructure.DeleteAsync.feature
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/MasterData.BusinessLogic.Implementations.Tests.csproj
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/MasterData.BusinessLogic.Implementations.Tests.csproj.DotSettings
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/StepDefs.Given.DimensionStructure.cs
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/StepDefs.Then.DimensionStructure.cs
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/StepDefs.Then.ListOperations.cs
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/StepDefs.When.DimensionStructure.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionStructure/DeleteDimensionStructureAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionStructure/GetActiveCountAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionStructure/GetActivesListAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionStructure/GetCountAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionStructure/MasterDataDimensionStructureBusinessLogic.cs
src/MasterData/MasterData.BusinessLogic.Interfaces/IMasterDataDimensionStructureBusinessLogic.cs
src/MasterData/MasterData.Controllers/Controllers/DimensionStructureController.cs

Logical delete function of DimensionStructure.
The feature comes with its minimal test set. The implementation contains StepDefs and other small pieces.

Feature: Logical delete of DimensionStructure

---

src/MasterData/MasterData.BusinessLogic.Implementations.Tests/DimensionStructure.DeleteAsync.feature
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/StepDefs.Then.ListOperations.cs
src/MasterData/MasterData.BusinessLogic.Implementations/SourceFormat/GetSourceFormatByIdWithActiveOnlyDimensionStructuresAndNodesAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/SourceFormat/GetSourceFormatByIdWithFullDimensionStructureTreeAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/SourceFormat/MasterDataSourceFormatBusinessLogic.cs
src/MasterData/MasterData.BusinessLogic.Interfaces/IMasterDataSourceFormatBusinessLogic.cs

Logical delete in the tree
These implementations and test cases provide a minimal feature set to be able to delete logically a dimensionstructure node in the tree. This functionality doesn't have any affect on the nodes. It will be a different story.

Feature: logically delete dimensionstructure

---

src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Unit.Tests/ControlPanel.BusinessLogic.Implementations.Unit.Tests.csproj
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/ControlPanel.BusinessLogic.Implementations.csproj
src/ControlPanel/ControlPanel.Ctx/ControlPanel.Ctx.csproj
src/Host/DiLib.FAST.Widgets/DiLib.FAST.Widgets.csproj
src/Host/FAST.Components/FAST.Components.csproj
src/Host/WebApp/WebApp.csproj
src/Host/WebUi/WebUi.csproj
src/MasterData/MasterData.BusinessLogic.Implementations.Tests/MasterData.BusinessLogic.Implementations.Tests.csproj
src/MasterData/MasterData.BusinessLogic.Implementations/MasterData.BusinessLogic.Implementations.csproj
src/MasterData/MasterData.Controllers.Integration.Tests/MasterData.Controllers.Integration.Tests.csproj
src/MasterData/MasterData.Ctx/MasterData.Ctx.csproj
src/Utils/IntegrationTestFactories/IntegrationTestFactories.csproj

chore: .Net packages bump to 3.1.9

---

src/MasterData/MasterData.BusinessLogic.Implementations.Tests/MasterData.BusinessLogic.Implementations.Tests.csproj

Chore/Specflow bump to 3.4.14

---

src/Host/WebUI.Test/WebUI.Test.csproj

Chore/Moq bump to 4.14.7

---

src/Host/DiLib.FAST.Widgets.Tests/DiLib.FAST.Widgets.Tests.csproj
src/Host/FAST.Components.Tests/FAST.Components.Tests.csproj

chore/bunit.web and bunit.xunit beta-11

---

src/MasterData/MasterData.BusinessLogic.Features/MasterData.BusinessLogic.Features.csproj
src/MasterData/MasterData.Web.Api.Features/MasterData.Web.Api.Features.csproj

Signed-off-by: Csányi András <sayusi.ando@gmail.com>

chore/Specflow 3.5.5

---

src/Host/WebUI.Test/WebUI.Test.csproj

Signed-off-by: Csányi András <sayusi.ando@gmail.com>

chore/Moq 4.15.1

---

src/ControlPanel/ControlPanel.Validators/ControlPanel.Validators.csproj
src/MasterData/MasterData.Validators/MasterData.Validators.csproj

Signed-off-by: SayusiAndo <sayusi.ando@gmail.com>

chore/FluentValidation 9.3.0

---

src/Host/WebApp/WebApp.csproj
src/MasterData/MasterData.BusinessLogic.Features/MasterData.BusinessLogic.Features.csproj

Signed-off-by: SayusiAndo <sayusi.ando@gmail.com>

chore/Npgsql.EntityFrameworkCore.PostgreSQL 5.0.0

---

src/Host/WebUi/WebUi.csproj
src/MasterData/MasterData.BusinessLogic.Features.Tests/MasterData.BusinessLogic.Features.Tests.csproj
src/MasterData/MasterData.Web.Api.Features.Tests/MasterData.Web.Api.Features.Tests.csproj

chore/nuget bump 02-19

---

src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Unit.Tests/ControlPanel.BusinessLogic.Implementations.Unit.Tests.csproj
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/ControlPanel.BusinessLogic.Implementations.csproj
src/ControlPanel/ControlPanel.Ctx/ControlPanel.Ctx.csproj
src/ControlPanel/ControlPanel.Validators/ControlPanel.Validators.csproj
src/Host/DiLib.FAST.Widgets/DiLib.FAST.Widgets.csproj
src/Host/FAST.Components/FAST.Components.csproj
src/Host/WebApp/WebApp.csproj
src/MasterData/MasterData.BusinessLogic.Features.Tests/MasterData.BusinessLogic.Features.Tests.csproj
src/MasterData/MasterData.Controllers.Integration.Tests/MasterData.Controllers.Integration.Tests.csproj
src/MasterData/MasterData.Ctx/MasterData.Ctx.csproj
src/MasterData/MasterData.Validators/MasterData.Validators.csproj
src/MasterData/MasterData.Web.Api.Features.Tests/MasterData.Web.Api.Features.Tests.csproj
src/Utils/IntegrationTestFactories/IntegrationTestFactories.csproj

Signed-off-by: AndrasCsanyi <sayusi.ando@gmail.com>

chore: bump nuget packages

---

src/ControlPanel/ControlPanel.Validators/ControlPanel.Validators.csproj
src/ControlPanel/ControlPanel.WebApi.Client/ControlPanel.WebApi.Client.csproj
src/Host/WebUi/WebUi.csproj
src/MasterData/MasterData.BusinessLogic.Features.Tests/MasterData.BusinessLogic.Features.Tests.csproj
src/MasterData/MasterData.Validators/MasterData.Validators.csproj
src/MasterData/MasterData.Web.Api.Features.Tests/MasterData.Web.Api.Features.Tests.csproj
src/MasterData/MasterData.WebApi.Client/MasterData.WebApi.Client.csproj
src/Utils/DiLibHttpClient/DiLibHttpClient.csproj

chore: bump nuget

---

src/MasterData/MasterData.BusinessLogic.Implementations/Dimension/AddDimensionAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/Dimension/DeleteDimensionAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/Dimension/UpdateDimensionAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionStructure/AddAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionStructure/DeleteAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionStructure/GetByIdAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionStructure/RemoveChildDimensionStructureAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionStructure/RemoveDimensionFromDimensionStructureAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionStructure/RemoveDimensionStructureFromSourceFormat.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionStructure/UpdateAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionStructureNode/AddAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionStructureNode/CreateRootNodeAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionValue/AddDimensionValueAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionValue/CountDimensionValues.cs
src/MasterData/MasterData.BusinessLogic.Implementations/DimensionValue/ModifyDimensionValue.cs
src/MasterData/MasterData.BusinessLogic.Implementations/SourceFormat/AddAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/SourceFormat/CountSourceFormatAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/SourceFormat/DeleteAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/SourceFormat/GetByIdAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/SourceFormat/GetSourceFormatByIdWithActiveDimensionStructureTreeAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/SourceFormat/InactivateAsync.cs
src/MasterData/MasterData.BusinessLogic.Implementations/SourceFormat/UpdateAsync.cs
src/MasterData/MasterData.Web.Api.Features.Tests/DimensionStructure/DeleteAsync.Validation.feature

FluentValidator deprecated its `ValidateAndThrowAsync()` method. This PR is about using the recommended way of validating.
The PR also contains an ignored test. The WebApi testing requires significant rework as it is overcomplicated.

chore: update fluentvalidator

---

src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Unit.Tests/ControlPanel.BusinessLogic.Implementations.Unit.Tests.csproj
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/ControlPanel.BusinessLogic.Implementations.csproj
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/Menu/AddAsync.cs
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/Menu/DeleteAsync.cs
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/Menu/FindAsync.cs
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/Module/AddAsync.cs
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/Module/DeleteAsync.cs
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/Module/ModifyAsync.cs
src/ControlPanel/ControlPanel.Ctx/ControlPanel.Ctx.csproj
src/ControlPanel/ControlPanel.Validators/ControlPanel.Validators.csproj
src/Host/DiLib.FAST.Widgets.Tests/DiLib.FAST.Widgets.Tests.csproj
src/Host/DiLib.FAST.Widgets/DiLib.FAST.Widgets.csproj
src/Host/FAST.Components.Tests/FAST.Components.Tests.csproj
src/Host/FAST.Components/FAST.Components.csproj
src/Host/WebApp/WebApp.csproj
src/MasterData/MasterData.BusinessLogic.Features.Tests/MasterData.BusinessLogic.Features.Tests.csproj
src/MasterData/MasterData.BusinessLogic.Implementations/SourceFormat/RemoveRootDimensionStructureNodeAsync.cs
src/MasterData/MasterData.Controllers.Integration.Tests/MasterData.Controllers.Integration.Tests.csproj
src/MasterData/MasterData.Ctx/MasterData.Ctx.csproj
src/MasterData/MasterData.Validators/MasterData.Validators.csproj
src/MasterData/MasterData.Web.Api.Features.Tests/MasterData.Web.Api.Features.Tests.csproj
src/Utils/IntegrationTestFactories/IntegrationTestFactories.csproj

Signed-off-by: AndrasCsanyi <sayusi.ando@gmail.com>

chore: bump nuget, and fix FluentValidator issues brought by upgrade

---

src/MasterData/MasterData.BusinessLogic.Features.Tests/StepDefinitions/StepDefinitions.Utils.cs

chore: coverage align

---

src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Unit.Tests/TestBase.cs
src/MasterData/MasterData.BusinessLogic.ViewModels.Unit.Tests/DimensionStructureQueryObjectShould.cs
src/MasterData/MasterData.DomainModel.Unit.Tests/SourceFormatDimensionStructureNode_Should.cs
src/Utils/Guard.Tests/IntAreNotEqualsShould.cs
src/Utils/Guard.Tests/LongAreNotEqualShould.cs
src/Utils/Guard.Tests/StringGuardShould.cs

chore: excluding files from coverage

---

src/ControlPanel/ControlPanel.Validators/ControlPanel.Validators.csproj
src/Host/DiLib.FAST.Widgets.Tests/DiLib.FAST.Widgets.Tests.csproj
src/Host/FAST.Components.Tests/FAST.Components.Tests.csproj
src/Host/WebApp/WebApp.csproj
src/MasterData/MasterData.BusinessLogic.Features.Tests/MasterData.BusinessLogic.Features.Tests.csproj
src/MasterData/MasterData.Validators/MasterData.Validators.csproj

This PR  contains bumps for the following nuget packages:
- FluentValidation
- Npgsql
- bunit

chore: nuget bumps

---

azure-pipelines.yml

fix(sonar): coverage fix

---

codecov.yml

fix: codecov

---

src/MasterData/MasterData.BusinessLogic.Tests.Integration/SourceFormat/SourceFormat_AddAsync_Should.cs
src/MasterData/MasterData.BusinessLogic.Tests.Integration/TestBase.cs

refactor: add integration test covering SourceFormat.AddAsync

---

src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Unit.Tests/ControlPanel.BusinessLogic.Implementations.Unit.Tests.csproj
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/ControlPanel.BusinessLogic.Implementations.csproj
src/ControlPanel/ControlPanel.Ctx/ControlPanel.Ctx.csproj
src/Host/DiLib.FAST.Widgets/DiLib.FAST.Widgets.csproj
src/Host/FAST.Components/FAST.Components.csproj
src/Host/WebApp/WebApp.csproj
src/MasterData/MasterData.BusinessLogic.Features.Tests/MasterData.BusinessLogic.Features.Tests.csproj
src/MasterData/MasterData.BusinessLogic.Tests.Integration/MasterData.BusinessLogic.Tests.Integration.csproj
src/MasterData/MasterData.Controllers.Integration.Tests/MasterData.Controllers.Integration.Tests.csproj
src/MasterData/MasterData.Ctx/MasterData.Ctx.csproj
src/MasterData/MasterData.StepDefinitions/MasterData.StepDefinitions.csproj
src/MasterData/MasterData.Web.Api.Features.Tests/MasterData.Web.Api.Features.Tests.csproj
src/Utils/IntegrationTestFactories/IntegrationTestFactories.csproj

chore: nuget bump

---

azure-pipelines.yml
src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Unit.Tests/ControlPanel.BusinessLogic.Implementations.Unit.Tests.csproj
src/ControlPanel/ControlPanel.WebApi.Client.Unit.Tests/ControlPanel.WebApi.Client.Unit.Tests.csproj
src/DigitalLibrary.sln
src/Host/DiLib.FAST.Widgets.Tests/DiLib.FAST.Widgets.Tests.csproj
src/Host/FAST.Components.Tests/FAST.Components.Tests.csproj
src/Host/WebUI.Test/WebUI.Test.csproj
src/MasterData/MasterData.BusinessLogic.Features.Tests/MasterData.BusinessLogic.Features.Tests.csproj
src/MasterData/MasterData.BusinessLogic.Tests.Integration/MasterData.BusinessLogic.Tests.Integration.csproj
src/MasterData/MasterData.BusinessLogic.ViewModels.Unit.Tests/MasterData.BusinessLogic.ViewModels.Unit.Tests.csproj
src/MasterData/MasterData.Controllers.Integration.Tests/MasterData.Controllers.Integration.Tests.csproj
src/MasterData/MasterData.Controllers.Unit.Tests/MasterData.Controllers.Unit.Tests.csproj
src/MasterData/MasterData.DomainModel.Unit.Tests/MasterData.DomainModel.Unit.Tests.csproj
src/MasterData/MasterData.Validators.Test/MasterData.Validators.Test.csproj
src/MasterData/MasterData.Web.Api.Features.Tests/MasterData.Web.Api.Features.Tests.csproj
src/Utils/Guard.Tests/Guard.Tests.csproj
src/Utils/TestHelper.Unit.Test/TestHelper.Unit.Test.csproj

chore: remove codecov

---

src/Host/FAST.Components.Tests/Components/Anchor/Anchor_Should.cs
src/Host/FAST.Components/Components/Anchor/Anchor.razor
src/Host/FAST.Components/Components/Anchor/Anchor.razor.cs

feature: add fast-anchor

---

azure-pipelines.yml
src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Unit.Tests/ControlPanel.BusinessLogic.Implementations.Unit.Tests.csproj
src/ControlPanel/ControlPanel.WebApi.Client.Unit.Tests/ControlPanel.WebApi.Client.Unit.Tests.csproj
src/Host/DiLib.FAST.Widgets.Tests/DiLib.FAST.Widgets.Tests.csproj
src/Host/FAST.Components.Tests/FAST.Components.Tests.csproj
src/Host/WebUI.Test/WebUI.Test.csproj
src/MasterData/MasterData.BusinessLogic.Features.Tests/MasterData.BusinessLogic.Features.Tests.csproj
src/MasterData/MasterData.BusinessLogic.Tests.Integration/MasterData.BusinessLogic.Tests.Integration.csproj
src/MasterData/MasterData.BusinessLogic.ViewModels.Unit.Tests/MasterData.BusinessLogic.ViewModels.Unit.Tests.csproj
src/MasterData/MasterData.Controllers.Integration.Tests/MasterData.Controllers.Integration.Tests.csproj
src/MasterData/MasterData.Controllers.Unit.Tests/MasterData.Controllers.Unit.Tests.csproj
src/MasterData/MasterData.DomainModel.Unit.Tests/MasterData.DomainModel.Unit.Tests.csproj
src/MasterData/MasterData.Validators.Test/MasterData.Validators.Test.csproj
src/MasterData/MasterData.Web.Api.Features.Tests/MasterData.Web.Api.Features.Tests.csproj
src/Utils/Guard.Tests/Guard.Tests.csproj
src/Utils/TestHelper.Unit.Test/TestHelper.Unit.Test.csproj

feature: sonarcloud

---

src/sonar.xml

feat: sonar

---

azure-pipelines.yml
src/MasterData/MasterData.BusinessLogic.Tests.Integration/SourceFormat/GetDimensionStructureNodeAsync_InputValidation_Should.cs
src/MasterData/MasterData.Validators/MasterDataDimensionValueValidator.cs

refacor: increase coverage

---

src/Host/FAST.Components.Tests/Accordion/AccordionItem_Should.cs
src/Host/FAST.Components.Tests/Accordion/Accordion_Should.cs
src/Host/FAST.Components.Tests/Anchor/Anchor_Should.cs
src/Host/FAST.Components.Tests/Badge/Badge_Should.cs
src/Host/FAST.Components/ComponentApis.cs
src/Host/FAST.Components/Components/Badge/Badge.razor
src/Host/FAST.Components/Components/Badge/Badge.razor.cs
src/Host/FAST.Components/Components/Badge/Badge.razor.css
src/Host/FAST.Components/FAST.Components.csproj

feature: fast badge

---

src/MasterData/MasterData.BusinessLogic.Implementations/SourceFormat/AppendDimensionStructureNodeToTreeAsync.cs
src/MasterData/MasterData.BusinessLogic.Tests.Integration/DimensionStructure/GetByIdAsync_Validation_Should.cs
src/MasterData/MasterData.BusinessLogic.Tests.Integration/SourceFormat/AppendDimensionStructureNodeAsync_Should.cs
src/MasterData/MasterData.BusinessLogic.Tests.Integration/SourceFormat/DeleteDimensionStructureNodeAsync_Should.cs
src/MasterData/MasterData.BusinessLogic.Tests.Integration/SourceFormat/GetAmountOfDimensionStructureNodeOfSourceFormatAsync_InputValidation_Should.cs
src/MasterData/MasterData.BusinessLogic.Tests.Integration/SourceFormat/GetAmountOfDimensionStructureNodeOfSourceFormatAsync_Should.cs
src/MasterData/MasterData.BusinessLogic.Tests.Integration/SourceFormat/GetDimensionStructureNodeAsync_InputValidation_Should.cs

refactor: increase source format test coverage

---

src/ControlPanel/ControlPanel.BusinessLogic.Implementations.Unit.Tests/ControlPanel.BusinessLogic.Implementations.Unit.Tests.csproj
src/ControlPanel/ControlPanel.BusinessLogic.Implementations/ControlPanel.BusinessLogic.Implementations.csproj
src/ControlPanel/ControlPanel.Ctx/ControlPanel.Ctx.csproj
src/ControlPanel/ControlPanel.Validators/ControlPanel.Validators.csproj
src/ControlPanel/ControlPanel.WebApi.Client.Unit.Tests/ControlPanel.WebApi.Client.Unit.Tests.csproj
src/Host/DiLib.FAST.Widgets.Tests/DiLib.FAST.Widgets.Tests.csproj
src/Host/DiLib.FAST.Widgets/DiLib.FAST.Widgets.csproj
src/Host/FAST.Components.Tests/FAST.Components.Tests.csproj
src/Host/FAST.Components/FAST.Components.csproj
src/Host/WebApp/WebApp.csproj
src/Host/WebUI.Test/WebUI.Test.csproj
src/MasterData/MasterData.BusinessLogic.Tests.Integration/MasterData.BusinessLogic.Tests.Integration.csproj
src/MasterData/MasterData.BusinessLogic.ViewModels.Unit.Tests/MasterData.BusinessLogic.ViewModels.Unit.Tests.csproj
src/MasterData/MasterData.Controllers.Integration.Tests/MasterData.Controllers.Integration.Tests.csproj
src/MasterData/MasterData.Controllers.Unit.Tests/MasterData.Controllers.Unit.Tests.csproj
src/MasterData/MasterData.Ctx/MasterData.Ctx.csproj
src/MasterData/MasterData.DomainModel.Unit.Tests/MasterData.DomainModel.Unit.Tests.csproj
src/MasterData/MasterData.StepDefinitions/MasterData.StepDefinitions.csproj
src/MasterData/MasterData.Validators.Test/MasterData.Validators.Test.csproj
src/MasterData/MasterData.Validators/MasterData.Validators.csproj
src/MasterData/MasterData.Web.Api.Features.Tests/MasterData.Web.Api.Features.Tests.csproj
src/Utils/Guard.Tests/Guard.Tests.csproj
src/Utils/IntegrationTestFactories/IntegrationTestFactories.csproj
src/Utils/TestHelper.Unit.Test/TestHelper.Unit.Test.csproj

chore: upgrade nuget packages

---

src/MasterData/MasterData.BusinessLogic.Tests.Integration/SourceFormat/DeleteDimensionStructureNodeAsync_Should.cs
src/MasterData/MasterData.BusinessLogic.Tests.Integration/TestBase.cs

fix(sourceformat): test case covering child node cleanup when node is deleted

---

src/MasterData/MasterData.BusinessLogic.Implementations/SourceFormat/GetAmountOfDimensionStructureNodeOfSourceFormatAsync.cs
src/MasterData/MasterData.BusinessLogic.Interfaces/IMasterDataSourceFormatBusinessLogic.cs
src/MasterData/MasterData.BusinessLogic.Tests.Integration/SourceFormat/DeleteDimensionStructureNodeAsync_Should.cs
src/MasterData/MasterData.BusinessLogic.Tests.Integration/TestBase.cs
src/MasterData/MasterData.Validators/SourceFormatValidator.cs
src/MasterData/MasterData.Validators/SourceFormatValidatorRulesets.cs

When DimensionStructureNode is deleted from the tree then its children nodes should be deleted too. This PR brings further tests convering this functionality. It also brings a small reforct with the following two items:
- SourceFormat management Api is extended an overload method which makes possible to request amount of DimensionStructureNodes of a SourceFormat by SourceFormat id too
- the extension above made possible to remove a validation rule

DSN tree mgmt tests

---

src/DigitalLibrary.sln
src/Utils/DiLibHttpClient.Tests.Unit/DeleteAsync_Should.cs
src/Utils/DiLibHttpClient.Tests.Unit/DiLibHttpClient.Tests.Unit.csproj
src/Utils/DiLibHttpClient.Tests.Unit/Example.cs
src/Utils/DiLibHttpClient.Tests.Unit/ExampleResult.cs
src/Utils/DiLibHttpClient.Tests.Unit/GetAsync_Should.cs
src/Utils/DiLibHttpClient.Tests.Unit/PostAsync_Should.cs
src/Utils/DiLibHttpClient.Tests.Unit/PutAsync_Should.cs
src/Utils/DiLibHttpClient.Tests.Unit/SpecialDataType.cs
src/Utils/DiLibHttpClient.Tests.Unit/TestBase.cs
src/Utils/DiLibHttpClient/DiLibHttpClient.cs
src/sonar.xml

refactor: dilib http client refactor
